# Generated by Django 5.0.14 on 2026-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='custom_category',
            field=models.CharField(blank=True, help_text="User-provided category if 'Other' is selected", max_length=100, null=True),
        ),
    ]
