# Generated by Django 5.0.14 on 2026-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
