# Generated by Django 5.0.14 on 2026-03-26 08:29

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=attachments.models.get_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('phash', models.CharField(db_index=True, max_length=64, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Scan'), ('SCANNING', 'Scanning/Processing'), ('CLEAN', 'Clean'), ('MALICIOUS', 'Malicious - Quarantined'), ('ERROR', 'Processing Error')], default='PENDING', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
            ],
        ),
    ]
