# Generated by Django 5.0.14 on 2026-03-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['report', 'processing_status'], name='attachments_report__525070_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['sha256_hash'], name='attachments_sha256__0fea80_idx'),
        ),
    ]
